FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt upgrade -y && apt install -y \
    git curl wget unzip zip tar gzip bzip2 xz-utils nano vim htop tree \
    build-essential clang cmake make ninja-build \
    python3 python3-pip python3-venv \
    nodejs npm \
    debootstrap squashfs-tools xorriso \
    grub-pc-bin grub-efi-amd64-bin mtools dosfstools \
    isolinux syslinux-common rsync parted gdisk \
    qemu-system-x86 qemu-utils \
    sudo ca-certificates gnupg lsb-release \
    && apt clean

WORKDIR /workspace

CMD ["/bin/bash"]
