#!/bin/sh
set -eu

lb config noauto \
  --mode debian \
  --architectures amd64 \
  --distribution trixie \
  --archive-areas "main contrib non-free-firmware" \
  --debian-installer false \
  --binary-images iso-hybrid \
  --mirror-bootstrap "http://deb.debian.org/debian/" \
  --mirror-chroot "http://deb.debian.org/debian/" \
  --mirror-binary "http://deb.debian.org/debian/" \
  --mirror-binary-security "http://security.debian.org/debian-security/" \
  --bootappend-live "boot=live components hostname=penos username=penos quiet splash" \
  --iso-application "PENOS" \
  --iso-publisher "INDEVSTUDIO" \
  --iso-volume "PENOS_ALPHA" \
  "${@}"
